name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - main
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          repository: AmbientPlatypus/test_repo
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config user.email overseer@gwgs.net
          git config user.name AmbientPlatypus
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
