name: Send submodule updates to parent repo

on:
  push:
    branches: 
      - main
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }} # `GH_PAT` is a secret that contains your PAT
          repository: AmbientPlatypus/test_repo
          submodules: true

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add --all
          git commit -m "Update submodules" || echo "No changes to commit"
          git push
